name: 'Streamlit Community Cloud Wake'

 # 触发条件
on:
  push:
  watch:
    types: [started]
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨 1 点执行

jobs:
  curl-my-site:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'

         # 向站点发送 GET 请求
         run: |                                   
           curl https://digital-assistant.streamlit.app/
